### ISSUE TITLE
JSをビューからJSファイルに移動、APIキーはcredentialsを使う

### ISSUE THREAD

**Issue by satou-haruka-37** [satou-haruka-37/hokkaido_travel#211]

**Comment by satou-haruka-37** [comment]
リファクタリングの1つ

**Comment by satou-haruka-37** [comment]
アプリ開発のことで担当講師の方に相談したいです。
JSをたくさん使っているのですが、
全部ビューファイルに書いてしまっています。
app/javascript配下にJSファイルを作ってちゃんとそちらに移したいのですが、
まずapp/javascriptのディレクトリ構造について理解できておらず、
色々なコードが一緒になっていたり、
似たような動作でも、対応するビューによって対応するidが違ったりして、なんの勉強から始めればいいのか、どこから手をつけていいかわからない状態です。
何かヒントを貰えたら嬉しいです🙇

ほとんどのビューファイルにJSが記載されていますが、
例えば[app/views/posts/index.html.erb](https://github.com/satou-haruka-37/hokkaido_travel/blob/main/app/views/posts/index.html.erb)のような現状です。

**Comment by Tsuchiya2** [comment]
issue対応ありがとうございます。
以下コメントになります。

---

■分類を行う
・issueを読むとJavaScript周りを綺麗にしたいというのは伝わりました。ただ、Hotriew, 特定のページのみで動いてほしいjsファイル, アプリ全体でどこでも動いてほしいjsファイル...etcがあるかと思います。まずはどのファイルに、どういった用途のJavaScriptがビューに書かれてしまっているかをまとめると良いかと思います。

■全体に影響を与えるjsファイルをapp/javascript/配下で読み込まれるようにする
・例えば、どのページにおいてもヘッダーの`〇〇`ボタンを押すと、投稿用のモーダルが表示され、入力を行って`投稿`ボタンを押すと投稿できる。といったJavaScriptがあるならば、そちらから対応していきましょう。
・該当のJavaScriptの記載をapp/javascript配下にjsファイルを用意して、そちらに後程記載を移動します。（以降、hoge.jsとします。）
・まずは、マニフェストファイルであるapp/javacript/application.jsでhoge.jsが読み込まれるようにするために以下の手順で確認しながら進めます。

```
1. hoge.jsにconsloe.log('hoge.js読み込み確認')
2. app/javascript/application.jsでhoge.jsを読み込む記載をします。
3. サーバーを立ち上げて、ブラウザの検証ツールのコンソールに「hoge.js読み込み確認」が表示されていればOKです。表示されないとしたら、2の記載ではhoge.jsが読み込まれていないので、パスが正しくない可能性があります。該当の文字列が表示されるように修正しましょう。
```

＊個々のページでのみ使用されるJavaScriptも上記の流れで反映させていくのは同様です。

一旦、生成したjsファイルがマニフェストファイルに正しく読み込まれているか確認していくところから行いましょう！

---

> 確認ダイアログなどの簡単なJSから移そうと思い、app/javascript/destroy-dialog.jsを作成。しかし、HTMLの方にonclickで書いていたので（JS側に、document.getElementByIdと書くのではなく）
コードの書き方から変えないといけない？と思いました。
また、Google Mapの中でやりたい動作のJSをすべて、変数のスコープがわからず、function initMap() {〜の中にすべて書いてしまっているinitMap()関数がすごく大きくなっているような箇所もあり、
先にJSのコードそのもののリファクタリングも必要なのではないか？と思いました。

JSのコードそのもののリファクタリングは、まずはビューにscriptタグを設けている状態を脱して、以下を満たせてからで良いかと思います。どれか1つでもまだのものがあれば、そちらを優先した方が良いかと思います。

```
- scriptタグを用いていない状態
- 他の機能実装は全て終わっている
- RSpecのテストも書き終えている
```

**Comment by Tsuchiya2** [comment]
issueに書かれていたonclickの部分は、現状のmainブランチのapp/views/developer_notices/show.html.erbの以下の記載のことですかね。

```javascript
function check(){
    if(window.confirm('本当に削除しますか？')){
      return true;
    }
    else{
      window.alert('削除がキャンセルされました');
      return false;
    }
  }
```

Gemfile(turbo-rails), app/views/layouts/application.html.erbの以下の記載からtruboを使っているかと思います。

```
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
```

turboではありませんがRails6系でもturbolinksというものがあり、以下のように書いてもJavaScriptが動かないということがありました。（[参考記事](https://techtechmedia.com/turbolinks-rails/)）

```javascript
window.addEventListener('load', (event) => {
  // 処理内容
});
```

上記の参考記事はturbolinksですが、仕組み等はturboもほぼ同様です。もしturboを使う形でJavaScriptを動かすとなると、参考記事の`document.addEventListener('turbolinks:load', function() {`のように、`ページのロード後`といったようにイベントの記載してあげる必要があります。

（Railsガイドにそのような記載があったかと思い探してみましたがすぐに見つけられなかったので、[こちら](https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/event)を共有しておきますね）

jsファイルの読み込み後、記載を該当ファイルに移動しても動かないようであれば、上記に注意してみてください。

**Comment by satou-haruka-37** [comment]
お返事が遅くなりすみません。
詳しく回答していただきありがとうございます🙇
JSの基礎の部分だけ学習して、移せるところだけJSファイルに移動しました。

- 現状
修正したコードです↓
https://github.com/satou-haruka-37/hokkaido_travel/pull/270/commits/33975386cdc3f68323d0f4952c74e03be8fea8e8

- これから行いたいこと
  - 全てのJSファイルで`document.addEventListener('DOMContentLoaded', function() { `〜と書かないと動かず、全部に書きました。すると、必要のないページでJSが動いてその「IDが見つかりません」というエラーが大量に出ているのを修正したいです。
  - モーダルを開くというJSコードも今までは`views/shared/_modal.html.erb`というパーシャルに`<script>`タグで記載していたので、パーシャルが呼び出された時にモーダルが開くようになっていたが、モーダルを開くJSが全ページに適応されたらおかしなことになってしますので修正したいです。
  - .envのAPIキー埋め込み部分をJSファイルで動くように書き換えたいです。
  - ERBの埋め込みの部分を書き換えたいです。

- 質問したいこと
全てのJSファイルを関係ないビューでも全て読み込んでいる方法は合っているのでしょうか？

**Comment by Tsuchiya2** [comment]
> 全てのJSファイルを関係ないビューでも全て読み込んでいる方法は合っているのでしょうか？

「合っている」というのは認識が違うかと。基本的にプログラミングに100%の正解はありません。そのため「合っている」というのは適切ではないかと。Railsのアセット周りはどのようになっているかを考えると、JSファイルは個々に読み込むよりもアセットパイプラインなどを使って共通なものは全て読み込ませておくのがRails Wayと思います。

問題のモーダル部分に関して言えば、`views/shared/_modal.html.erb`で表示するというのも1つの考え方としては良いかと思います。

---

> .envのAPIキー埋め込み部分をJSファイルで動くように書き換えたいです。

まずどのファイルにAPIキーがあるかなどが分からないため、曖昧な回答になりますが、credentials.yml で環境変数化して、それを呼び出せばよいかと思います。

- https://plog.kobacchi.com/rails-set-credentials/
- https://zenn.dev/yuna0960740/articles/98531e13665815 （ENVの部分をcredentialsに置き換えて見てみてください）

**Comment by satou-haruka-37** [comment]
返答ありがとうございます。
すみません、表現が適切ではありませんでした🙇
また、Rails Way等についても教えていただきありがとうございます。調べて勉強します。
　　
- 現状
  - Google MapのJSコードは、APIキーのscriptタグはERBに残し、ロジックの部分だけJSファイルに移すことでうまくいきました。
  （ビューファイル内のcredentialsはFly.ioでエラーが出るため.envを使っています。）
  - モーダルの部分もコメントいただいたように、パーシャルが呼び出される→パーシャル内のscriptタグが実行される→パーシャルが開くようにしており、現状他の方法が思いつくまでこの方法で行こうと思います。
　　
- 試したこと
  - [調べた記事](https://qiita.com/masamitsu-konya/items/84ef7a63333b66713512)を参考に、JSファイル内に`@post.latitude`などを直接埋め込もうとすると、Railsのフロントエンドとバックエンドでのデータのやり取りは簡単なものではなく、直接埋め込むことはできないようでした。
  - ロボらんてくんの助言を元に、HTML`data`属性を使う方法を試しました。
  ```js
  // ERBファイルで記載
  <div id="postshow-map" data-latitude="<%= @post.latitude %>" data-longitude="<%= @post.longitude %>"></div>
  
  // JSファイル内に記載
  document.addEventListener("DOMContentLoaded", function() {
    const mapElement = document.getElementById("postshow-map");
    const latitude = parseFloat(mapElement.getAttribute('data-latitude'));
    const longitude = parseFloat(mapElement.getAttribute('data-longitude'));
  });
  ```
  - esbuildのbuildの設定ファイルなどを作成・使用してバックエンドから取得したデータをJSファイル内で変数として使えるように渡す方法を調べましたが、良い記事が見つけられませんでした。

　　
- 行いたいこと・質問したいこと
残りは下記の2つのビューファイルだけなのですが、元々のロジック自体にRubyを混ぜて作ってしまっています。（JS内に`<%= @post.latitude %>`など）
行いたいことは、
・バックエンドのデータをJSに渡す方法を見つけたい
・渡す方法があれば、JSのコード内に埋め込んでいるERBをJSに書き換える
  
  ですが、やり方が見つけられず詰まってしまったので相談させていただきました。

  - [app/views/posts/index.html.erb](https://github.com/satou-haruka-37/hokkaido_travel/blob/main/app/views/posts/index.html.erb)
  - [app/views/posts/show.html.erb](https://github.com/satou-haruka-37/hokkaido_travel/blob/main/app/views/posts/show.html.erb)

**Comment by Tsuchiya2** [comment]
そうですね...`@post`などのところは、JavaScriptからRails側にリクエストを飛ばして、その帰ってきたレスポンスを`@post`のところで使用する感じとかで行けそうな気がします。

ただ見栄え的にユーザーにとっては、あまりインパクトが無い部分なので他に対応が必要なものがあればそちらを優先的に取り組む方が良いかと思います。

↑のイメージですがこんな流れです。
```
- ページの読み込みが完了したらJavaScriptからRailsに対してリクエストを投げる
- Rails側は受け取ったリクエストの情報をシリアライズしてjson形式で返す
- 帰ってきたjson形式のデータをJavaScript側で受け取る
- 受け取ったデータを使って以降のJavaScript処理を行う
```

（Fetch APIとか他にもリクエストを飛ばす方法はあるので調べて試してみるとよいかと思います）

- https://zenn.dev/junki555/articles/e119439e46a85e

**Comment by satou-haruka-37** [comment]
JSとRubyの混ざったコードの部分は一旦保留で、RSpecなど他のことを優先し、このISSUEはcloseします。
