### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [satou-haruka-37/hokkaido_travel#229]
MVPリリースお疲れ様でした。
以下レビュー内容になります。

---

■READMEから課題解決する実装がされているか＆動いているか
・確認できました。LGTMです。

■改善の提案
・app/controllers/posts_controller.rbの`validate_images`のところは、コントローラーの責務からすると、ここではなくモデルなどに書くべき記載かと思うので修正しましょう。

■その他
・Outh0でのログインに関しては、違和感等はありませんでしたので現状のままで良いかと思います。

---

全体的に完成度も高くて良かったかと思います。
技術の方も一定レベルに達していると感じました。
そのまま就活に臨んでも問題ないレベルですので、残りの開発と並行して就活の準備に取り組みましょう！

**Comment by Tsuchiya2** [comment]
--- 追記 ---
本リリースの大まかな日取りを教えてください。
よろしくお願いいたします。

**Comment by satou-haruka-37** [comment]
レビューしていただきありがとうございます🙇

- `validate_images`メソッドは、app/models/post.rbに移動しました。
- GCPなどのAPI関係の申請は特にしていませんが、問題なく機能は使えているので申請等は不要なのでしょうか？
- 本リリースの日程は1/20日ごろで考えています。

**Comment by Tsuchiya2** [comment]
ご返信ありがとうございます。
引き続き開発頑張ってください。
